paws_and_tails/config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post '/login/create', to: 'sessions#create'

  resources :users
  resources :sessions

  get '/breeders/redesigned_destroy/:id', to: "breeders#redesigned_destroy"
  get '/animals/redesigned_destroy/:id', to: "animals#redesigned_destroy"

  get '/messages/:to_user_id', to: "messages#show"
  post '/messages/api/new', to: "messages#create"
  get '/messages/inbox/show', to: "messages#inbox"

  post '/waitlists/join', to: "waitlists#join"
  post '/waitlists/leave', to: "waitlists#leave"
  get '/waitlists/manage/remove/:user_id/:animal_id', to: "waitlists#manage_remove"

  # get "/link", to: "users#link_user_with_breeder"

  # get 'animal/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "animals#index"
  resources :animals
  resources :breeders

  post "/animals/api/sort_location", to: "animals#sort_location"

  match '*unmatched', to: 'application#not_found_method', via: :all

  # get "/animals", to: "animals#index"
  # get "/animals/:id", to: "animals#show"
end

paws_and_tails/app/models/animal.rb
class Animal < ApplicationRecord
  validates :name, presence: true
  validates :animal_type, presence: true
  validates :breed, presence: true
  validates :price, presence: true, numericality: { only_numeric: true }
  validates :anticipated_birthday, presence: true
  validates :breeder_id, presence: true
  belongs_to :breeder

  def self.get_breeder(animal_id)
    animal = Animal.find(animal_id)
    breeder = Breeder.find(animal.breeder_id)
    return breeder
  end

  def self.search(search)
    return all unless search.present?

    joins(:breeder).where("animal_type LIKE :search OR breed LIKE :search OR animals.name LIKE :search OR breeders.name LIKE :search", search: "%#{search}%")
  end

  def self.location_refine(city, country)
    animals = nil
    if city.nil? && country.nil?
      # find unrestricted
      animals = Animal.all
    elsif !city.nil? && country.nil?
      # find city
      animals = Animal.joins(:breeder).where(breeders: {city: city})
    elsif city.nil? && !country.nil?
      # find country
      animals = Animal.joins(:breeder).where(breeders: {country: country})
    else
      # find city and country
      animals = Animal.joins(:breeder).where(breeders: {city: city, country: country})
    end
    return animals
  end
end

paws_and_tails/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  # before_action :has_auth, only: [:edit, :update, :destroy, :new]
  skip_before_action :verify_authenticity_token

  def index
    city = params[:city] == "Any City" ? nil : params[:city]
    country = params[:country] == "Any Country" ? nil : params[:country]
    sorting_method = params[:sorting] || "name"

    @animals = Animal.search(params[:search]).location_refine(city, country)

    if sorting_method == "breeder_id"
      @animals = @animals.includes(:breeder).order("breeders.name")
    elsif sorting_method != "city" && sorting_method != "country"
      @animals = @animals.order(sorting_method)
    else
      @animals = @animals.includes(:breeder).order("breeders.#{sorting_method}")
    end

    @cities = Breeder.get_city_all.sort
    @countries = Breeder.get_country_all.sort
    @is_admin = is_admin
  end

  # GET /animals/1
  def show
    @breeder = Animal.get_breeder(params[:id])
    @is_admin_or_current_breeder = is_admin_or_current_breeder
    if current_user.nil?
      @already_waitlist = false
    else
      @already_waitlist = Waitlist.exists?(animal_id: params[:id], user_id: current_user.id)
      if @already_waitlist
        this_waitlist = Waitlist.where(animal_id: params[:id], user_id: current_user.id).first
        @total_place = Waitlist.where(animal_id: params[:id]).count
        @current_place = Waitlist.where(animal_id: params[:id]).where("created_at < ?", this_waitlist.created_at).count + 1
      end
    end
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  def create
    this_animal_params = animal_params
    if this_animal_params[:breeder_id].nil?
      this_animal_params[:breeder_id] = UserToBreeder.get_breeder_id(current_user.id.to_s)
    end

    @animal = Animal.new(this_animal_params)

    if @animal.save
      redirect_to @animal, notice: 'Animal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /animals/1
  def update
    if @animal.update(animal_params)
      redirect_to @animal, notice: 'Animal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /animals/1
  # def destroy
  #   @animal.destroy
  #   redirect_to animals_url, notice: 'Animal was successfully destroyed.'
  # end

  def redesigned_destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_url, notice: 'Animal was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_animal
    @animal = Animal.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def animal_params
    params.require(:animal).permit(:name, :animal_type, :breed, :price, :anticipated_birthday, :breeder_id, :image_link)
  end
end

paws_and_tails/app/views/animals/_animal_grid.html.erb
<% animals_var.each do | animal | %>
  <div class="column is-4">
    <div class="card shadow-md is-cursor-pointer transform is-duration-300 hover-shadow-xl hover-translate-y">
      <div class="card-image">
        <figure class="image is-4by3">
          <% if animal.image_link.to_s == '' %>
            <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
          <% else %>
            <img src="<%= animal.image_link %>" alt="animal picture">
          <% end %>
        </figure>
      </div>
      <div class="card-content">
        <div class="media">
          <div class="media-content">
            <p class="title is-4"><%= link_to animal.name, animal_path(animal) %></p>
            <p class="subtitle is-6">@My breeder: <%= Animal.get_breeder(animal.id).name %></p>
          </div>
        </div>

        <div class="content">
          Animal Type: <%= animal.animal_type %>
          <br>
          Breed: <%= animal.breed %>
          <br>
          Price: <%= animal.price %>
          <br>
          Anticipated Birth: <%= animal.anticipated_birthday.getlocal.strftime("%m/%d/%Y") %>
          <br>
          <br>
          <strong>Location:</strong> <%= Animal.get_breeder(animal.id).city%>, <%= Animal.get_breeder(animal.id).country%>
        </div>
      </div>
    </div>
  </div>
<% end %>

paws_and_tails/app/views/animals/_form.html.erb
<%= form_for(@animal) do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% @animal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Animal Name", class:'label' %>
    <div class="control">
      <%= f.text_field :name, class:'input' %>
    </div>
  </div>
  <div class="field">
    <%= f.label :animal_type, "Animal Type", class: 'label' %>
    <div class="control">
      <%= f.text_field :animal_type, class: 'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :breed, "Animal Breed", class:'label' %>
    <div class="control">
      <%= f.text_field :breed, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :price, "Price", class:'label' %>
    <div class="control">
      <%= f.text_field :price, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :anticipated_birthday, "Anticipated Birthday", class:'label' %>
    <div class="control">
      <%= f.text_field :anticipated_birthday, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :image_link, "Image Link", class:'label' %>
    <div class="control">
      <%= f.text_field :image_link, class:'input' %>
    </div>
  </div>

  <% if current_user[:user_type].to_s == "admin" %>
    <div class="field">
      <%= f.label :breeder_id, "Breeder id", class:'label' %>
      <div class="control">
        <%= f.text_field :breeder_id, class:'input' %>
      </div>
    </div>
  <% end %>

  <div class="field">
    <div class="control">
      <%= f.submit 'Submit', class: 'button is-warning' %>
    </div>
  </div>
<% end %>

paws_and_tails/app/views/animals/edit.html.erb
<!--<h1>Editing Animal</h1>-->

<%#= render 'form' %>

<!--<%#= link_to 'Show', @animal %> |-->
<%#= link_to 'Back', animals_path %>


<div class="columns">
  <div class="column">
    <h3 class="title">Edit Animal</h3>
  </div>
</div>


<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= render 'form' %>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= link_to 'Cancel', animals_url, class: 'button' %>
  </div>
</div>

paws_and_tails/app/views/animals/index.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title">Find Animals Near You</h3>
    <p class="subtitle">Bring Your New Best Friend Home.</p>
  </div>
</div>

<br><br>


<div class="columns is-multiline is-centered is-mobile has-background-light">
  <%= form_with(url: animals_path, method: :get, local: true, html: { class: 'column is-12 has-text-centered' }) do |form| %>
    <%= form.label :search, 'Search', class: 'sr-only' %>
    <input type="hidden" name="sorting" id="sorting" value="name">
    <div class="column is-12" style="display: flex; justify-content: center;">
      <div class="field has-addons" style="max-width: 100%;">
        <div class="control is-expanded">
          <%= form.text_field :search, value: params[:search], class: 'input is-medium', placeholder: 'Search' %>
        </div>
        <div class="control">
          <%= form.select :city, @cities.unshift('Any City'), { selected: params[:city] || 'Any City' }, { class: 'input is-medium' } %>
        </div>
        <div class="control">
          <%= form.select :country, @countries.unshift('Any Country'), { selected: params[:country] || 'Any Country' }, { class: 'input is-medium' } %>
        </div>
        <div class="control">
          <%= form.submit 'Search', class: 'button is-warning is-medium' %>
        </div>
        <div class="control">
          <button id="reset-location" class="button is-warning is-medium is-light">Reset</button>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="columns">
  <div class="column is-12 has-text-center">
    <button id="sort-name" class="button is-small is-rounded animal-sort-button sort-name">Sort by Name</button>
    <button id="sort-breeder_id" class="button is-small is-rounded animal-sort-button sort-breeder_id">Sort by Breeder</button>
    <button id="sort-animal_type" class="button is-small is-rounded animal-sort-button sort-animal_type">Sort by Type</button>
    <button id="sort-breed" class="button is-small is-rounded animal-sort-button sort-breed">Sort by Breed</button>
    <button id="sort-price" class="button is-small is-rounded animal-sort-button sort-price">Sort by Price</button>
    <button id="sort-anticipated_birthday" class="button is-small is-rounded animal-sort-button sort-anticipated_birthday">Sort by Birth</button>
    <button id="sort-city" class="button is-small is-rounded animal-sort-button sort-city">Sort by City</button>
    <button id="sort-country" class="button is-small is-rounded animal-sort-button sort-country">Sort by Country</button>
  </div>
</div>

<br>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <div id="animals-container" class="columns is-multiline is-mobile">
      <%= render partial: "animal_grid", locals: {animals_var: @animals} %>
    </div>
  </div>
</div>


<% if @is_admin %>
  <div class="columns">
    <div class="column has-text-right">
      <%= link_to 'New Animal', new_animal_path, class:"button is-warning is-light" %>
    </div>
  </div>
<% end %>

paws_and_tails/app/views/animals/new.html.erb
<!--<h1>New Animal</h1>-->

<%#= render 'form' %>

<%#= link_to 'Back', animals_path %>


<div class="columns">
  <div class="column">
    <h3 class="title">Add a New Animal</h3>
  </div>
</div>



<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= render 'form' %>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= link_to 'Cancel', animals_url, class: 'button' %>
  </div>
</div>

paws_and_tails/app/views/animals/show.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title">Animal: <%= @animal.name %></h3>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-6 has-text-centered">
    <figure class="image is-4by3">
      <% if @animal.image_link.to_s == '' %>
        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="placeholder">
      <% else %>
        <img src="<%= @animal.image_link %>" alt="animal picture">
      <% end %>
    </figure>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <div class="box">
      <div class="columns">
        <div class="column is-4">
          Animal Type:
        </div>
        <div class="column is-8">
          <%= @animal.animal_type %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Breed:
        </div>
        <div class="column is-8">
          <%= @animal.breed %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Price:
        </div>
        <div class="column is-8">
          <%= @animal.price %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Anticipated Birthday:
        </div>
        <div class="column is-8">
          <%= @animal.anticipated_birthday.getlocal.strftime("%m/%d/%Y") %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Breeder:
        </div>
        <div class="column is-8">
          <%= link_to @breeder.name, breeder_path(@breeder) %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if !current_user.nil? && (current_user[:user_type].to_s == "admin" || UserToBreeder.get_user_id(@breeder.id.to_s).to_s == current_user.id.to_s) %>
  <div class="columns is-mobile is-centered">
    <div class="column is-10" style="border: 2px groove green">

      <div class="columns">
        <div class="column">
          <h3 class="is-size-4 has-background-white-ter has-text-centered">Breeder Panel</h3>
        </div>
      </div>

      <% @get_waitlists = Waitlist.where(animal_id: @animal.id).order(:created_at) %>

      <% if @get_waitlists.length == 0 %>
        <p class="has-text-centered"><br>Currently, there is no petfinder on this animal's waitlist.</p>
      <% else %>
        <div class="columns">
          <div class="column">
            <p>Waitlist size: <%= @get_waitlists.length %></p>
          </div>
        </div>

        <div class="columns">
          <div class="column">
            <strong>Petfinders:</strong>
          </div>
        </div>
        <div class="columns is-mobile is-centered">
          <div class="column is-6">
            <% @get_waitlists.each do | w | %>
              <div class="columns">
                <div class="column is-4">
                  <p><%= User.get_user_name w.user_id %></p>
                </div>
                <div class="column is-8">
                  <%= link_to "Remove from Waitlist", "/waitlists/manage/remove/" + w.user_id.to_s + "/" + @animal.id.to_s %>
                  &nbsp;
                  <%= link_to "Message Petfinder", "/messages/" + w.user_id.to_s %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <% if !current_user.nil? %>
    <div class="columns is-mobile is-centered">
      <div id="waitlist-display-column" class="column is-10 has-text-right">
        <% if @already_waitlist %>
          <p>Your current position: <%= @current_place %></p>
          <p>Total Waitlist: <%= @total_place %></p>
          <%= link_to "Leave Waitlist", "/waitlists/leave", class: 'button is-danger', id: 'leave-waitlist-btn' %>
        <% else %>
          <%= link_to "Join Animal Liter Waitlist", "/waitlists/join", class: 'button is-warning', id: 'join-waitlist-btn' %>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="columns is-mobile is-centered">
      <div class="column is-10 has-text-right">
        <%= link_to "Log In to Join Waitlist", "/login", class: 'button is-warning' %>
      </div>
    </div>
  <% end %>
<% end %>


<div class="columns is-mobile is-centered">
  <div class="column is-10 has-text-right">
    <%= link_to "Back", animals_path, class: 'button is-info' %>

    <% if @is_admin_or_current_breeder %>
      <%= link_to "Delete", "/animals/redesigned_destroy/" + @animal.id.to_s, class: 'button is-danger'%>
      <%= link_to "Edit", edit_animal_path(@animal), class: 'button is-warning' %>
    <% end %>
  </div>
</div>


<script>

    if (document.getElementById("leave-waitlist-btn")) {
        attachLeaveHandler();
    }

    if (document.getElementById("join-waitlist-btn")) {
        attachJoinHandler();
    }

    function attachJoinHandler() {
        document.getElementById('join-waitlist-btn').addEventListener("click", function (event) {
            event.preventDefault();

            fetch("/waitlists/join", {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json'
                    // 'X-Requested-With': 'XMLHttpRequest',
                    // 'X-CSRF-Token': token
                },
                body: JSON.stringify({
                    "animal_id": <%= @animal.id.to_s %>,
                    "user_id": <%= current_user.nil? ? "" : current_user.id.to_s %>
                }),
                credentials: 'same-origin'
            })
                .then(response => response.json())
                .then(data => {
                    const waitlistDisplayColumnSelector = document.getElementById("waitlist-display-column");
                    waitlistDisplayColumnSelector.replaceChildren();
                    waitlistDisplayColumnSelector.innerHTML += "<p>Your current position:" + data["current_place"] + "</p>"
                    waitlistDisplayColumnSelector.innerHTML += "<p>Total Waitlist:" + data["total_place"] + "</p>"
                    waitlistDisplayColumnSelector.innerHTML += "<a class='button is-danger' id='leave-waitlist-btn' href='/waitlists/leave'>Leave Waitlist</a>"
                    attachLeaveHandler();
                })
                .catch(error => {
                    console.log(error);
                })
        });
    }

    function attachLeaveHandler() {
        document.getElementById("leave-waitlist-btn").addEventListener("click", function (e) {
            e.preventDefault();
            fetch("/waitlists/leave", {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json'
                    // 'X-Requested-With': 'XMLHttpRequest',
                    // 'X-CSRF-Token': token
                },
                body: JSON.stringify({
                    "animal_id": <%= @animal.id.to_s %>,
                    "user_id": <%= current_user.nil? ? "" : current_user.id.to_s %>
                }),
                credentials: 'same-origin'
            })
                .then(response => response.json())
                .then(data => {
                    const waitlistDisplayColumnSelector = document.getElementById("waitlist-display-column");
                    waitlistDisplayColumnSelector.replaceChildren();
                    waitlistDisplayColumnSelector.innerHTML += "<a class='button is-warning' id='join-waitlist-btn' href='/waitlists/join'>Join Animal Liter Waitlist</a>"
                    attachJoinHandler();
                })
                .catch(error => {
                    console.log(error);
                })
        })
    }
</script>