paws_and_tails/config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  post '/login/create', to: 'sessions#create'

  resources :users
  resources :sessions

  get '/breeders/redesigned_destroy/:id', to: "breeders#redesigned_destroy"
  get '/animals/redesigned_destroy/:id', to: "animals#redesigned_destroy"

  get '/messages/:to_user_id', to: "messages#show"
  post '/messages/api/new', to: "messages#create"
  get '/messages/inbox/show', to: "messages#inbox"

  post '/waitlists/join', to: "waitlists#join"
  post '/waitlists/leave', to: "waitlists#leave"
  get '/waitlists/manage/remove/:user_id/:animal_id', to: "waitlists#manage_remove"

  # get "/link", to: "users#link_user_with_breeder"

  # get 'animal/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "animals#index"
  resources :animals
  resources :breeders

  post "/animals/api/sort_location", to: "animals#sort_location"

  match '*unmatched', to: 'application#not_found_method', via: :all

  # get "/animals", to: "animals#index"
  # get "/animals/:id", to: "animals#show"
end

paws_and_tails/app/models/breeder.rb
class Breeder < ApplicationRecord
  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :price_level, presence: true, format: {with: /\$+/}
  validates :address, presence: true
  validates :email, presence: true, email: true
  has_many :animals, dependent: :destroy

  def self.get_animals(breeder_id)
    animals = Animal.where(:breeder_id => breeder_id)
    return animals
  end

  def self.get_city_all
    Breeder.distinct.pluck(:city)
  end

  def self.get_country_all
    Breeder.distinct.pluck(:country)
  end
end

paws_and_tails/app/controllers/breeders_controller.rb
class BreedersController < ApplicationController
  before_action :set_breeder, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update]

  # GET /breeders
  def index
    @breeders = Breeder.all
    @is_admin = is_admin
  end

  # GET /breeders/1
  def show
    breeder_id = params[:id]
    @animals = Breeder.get_animals(breeder_id)
    @is_admin_or_current_breeder = is_admin_or_current_breeder
    @not_this_user = not_this_user

    @user_id = UserToBreeder.get_user_id(@breeder.id)
  end

  # GET /breeders/new
  def new
    if is_admin || (current_user.user_type.to_s == "breeder" && !UserToBreeder.exists?(user_id: current_user.id.to_s))
      @breeder = Breeder.new
    elsif !is_admin && UserToBreeder.exists?(user_id: current_user.id.to_s)
      flash[:notice] = "You have already linked with a breeder"
      redirect_to root_url
    else
      flash[:warning] = "You don't have the permission"
      redirect_to root_url
    end
  end

  # GET /breeders/1/edit
  def edit
  end

  # POST /breeders
  def create
    @breeder = Breeder.new(breeder_params)

    if @breeder.save
      if current_user.user_type.to_s != "admin"
        UserToBreeder.create!(:user_id => current_user.id.to_s, :breeder_id => @breeder.id)
      end
      redirect_to @breeder, notice: 'Breeder was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /breeders/1
  def update
    if @breeder.update(breeder_params)
      redirect_to @breeder, notice: 'Breeder was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /breeders/1
  # def destroy
  #   # redirect_to root_url
  #   # UserToBreeder.where(:breeder_id => @breeder.id).destroy
  #
  #   UserToBreeder.where(breeder_id: @breeder[:id]).first.destroy
  #
  #   @breeder.destroy
  #   redirect_to breeders_url, notice: 'Breeder was successfully destroyed.'
  # end

  def redesigned_destroy
    @breeder = Breeder.find(params[:id])
    UserToBreeder.where(breeder_id: params[:id]).first.destroy if UserToBreeder.exists?(breeder_id: params[:id])

    @breeder.destroy
    redirect_to breeders_url, notice: 'Breeder was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_breeder
    @breeder = Breeder.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def breeder_params
    params.require(:breeder).permit(:name, :city, :country, :price_level, :address, :email)
  end
end

paws_and_tails/app/views/breeders/_form.html.erb
<%= form_for(@breeder) do |f| %>
  <% if @breeder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@breeder.errors.count, "error") %> prohibited this breeder from being saved:</h2>

      <ul>
        <% @breeder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Breeder Name", class:'label' %>
    <div class="control">
      <%= f.text_field :name, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :email, "Email", class:'label' %>
    <div class="control">
      <%= f.text_field :email, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :city, "City", class:'label' %>
    <div class="control">
      <%= f.text_field :city, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :country, "Country", class:'label' %>
    <div class="control">
      <%= f.text_field :country, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :price_level, "Price Level", class:'label' %>
    <div class="control">
      <%= f.text_field :price_level, class:'input' %>
    </div>
  </div>

  <div class="field">
    <%= f.label :address, "Address", class:'label' %>
    <div class="control">
      <%= f.text_field :address, class:'input' %>
    </div>
  </div>


  <div class="field">
    <div class="control">
      <%= f.submit 'Submit', class: 'button is-warning' %>
    </div>
  </div>
<% end %>

paws_and_tails/app/views/breeders/edit.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title">Edit Breeder</h3>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= render 'form' %>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= link_to 'Cancel', breeders_url, class: 'button' %>
  </div>
</div>

paws_and_tails/app/views/breeders/index.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title">Find Breeders Near You</h3>
    <p class="subtitle">Bring Your New Best Friend Home.</p>
  </div>
</div>


<div class="columns is-mobile is-centered">
  <div class="column is-6">
    <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
      <thead>
      <tr>
        <th>Breeder Name</th>
        <th>Breeder City</th>
        <th>Breeder Country</th>
        <th>Price Level</th>
      </tr>
      </thead>
      <tbody>
      <% @breeders.each do |breeder| %>
        <tr>
          <td><%= link_to "#{breeder.name}", breeder_path(breeder) %></td>
          <td><%= breeder.city %></td>
          <td><%= breeder.country %></td>
          <td><%= breeder.price_level %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>



<% if @is_admin %>
  <div class="columns">
    <div class="column has-text-right">
      <%= link_to 'New Breeder', new_breeder_path, class:"button is-warning is-light" %>
    </div>
  </div>
<% end %>

paws_and_tails/app/views/breeders/new.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title">Add a New Breeder</h3>
  </div>
</div>


<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= render 'form' %>
  </div>
</div>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <%= link_to 'Cancel', breeders_url, class: 'button' %>
  </div>
</div>

paws_and_tails/app/views/breeders/show.html.erb
<div class="columns">
  <div class="column">
    <h3 class="title">Breeder: <%= @breeder.name %></h3>
  </div>
</div>


<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <div class="box">
      <div class="columns">
        <div class="column is-4">
          Breeder Email:
        </div>
        <div class="column is-8">
          <%= @breeder.email %>
          <button class="button is-rounded is-link is-light is-small" onclick="location.href='mailto:<%= @breeder.email %>';">Email Breeder</button>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Breeder City:
        </div>
        <div class="column is-8">
          <%= @breeder.city %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Breeder Country:
        </div>
        <div class="column is-8">
          <%= @breeder.country %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Price Level:
        </div>
        <div class="column is-8">
          <%= @breeder.price_level %>
        </div>
      </div>
      <div class="columns">
        <div class="column is-4">
          Breeder Address:
        </div>
        <div class="column is-8">
          <%= @breeder.address %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @not_this_user %>
  <div class="columns is-mobile is-centered">
    <div class="column is-10 has-text-right">
      <%= link_to "Message Breeder", "/messages/" + @user_id.to_s, class: 'button is-info' %>
    </div>
  </div>
<% end %>

<div class="columns is-mobile is-centered">
  <div class="column is-10">
    <div class="columns is-multiline is-mobile">
      <% @animals.each do | animal | %>
        <div class="column is-4">
          <div class="card shadow-md is-cursor-pointer transform is-duration-300 hover-shadow-xl hover-translate-y">
            <div class="card-image">
              <figure class="image is-4by3">
                <% if animal.image_link.to_s == '' %>
                  <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                <% else %>
                  <img src="<%= animal.image_link %>" alt="animal picture">
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <p class="title is-4"><%= link_to animal.name, animal_path(animal) %></p>
                  <p class="subtitle is-6">@My breeder: <%= Animal.get_breeder(animal.id).name %></p>
                </div>
              </div>

              <div class="content">
                Animal Type: <%= animal.animal_type %>
                <br>
                Breed: <%= animal.breed %>
                <br>
                Price: <%= animal.price %>
                <br>
                Anticipated Birth: <%= animal.anticipated_birthday.getlocal.strftime("%m/%d/%Y") %>
                <br>
                <br>
                <strong>Location:</strong> <%= Animal.get_breeder(animal.id).city%>, <%= Animal.get_breeder(animal.id).country%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



<div class="columns">
  <div class="column has-text-right">
    <%= link_to "Back", breeders_path, class: 'button is-info' %>

    <% if @is_admin_or_current_breeder %>
      <%= link_to "Delete", "/breeders/redesigned_destroy/" + @breeder.id.to_s, class: 'button is-danger'%>
      <%= link_to "Edit", edit_breeder_path(@breeder), class: 'button is-warning' %>
      <%= link_to 'New Animal', new_animal_path, class:"button is-warning is-light" %>
    <% end %>
  </div>
</div>